[tool.black]
line-length = 99

[tool.isort]
profile = "black"
line_length = 99
multi_line_output = 3
lines_after_imports = 2
default_section = "THIRDPARTY"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

